version: 2.1

jobs: # a basic unit of work in a run
 build: # your job name
  macos:
   xcode: 13.2.1 # indicate your selected version of Xcode
  steps: # a series of commands to run
   - checkout  # pull down code from your version control system.
   - run:
      name: Run Unit Tests
      command: xcodebuild test -workspace CircleCI.xcworkspace -scheme CircleCI -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4'
   - run:
      name: Build Application
      command: xcodebuild -workspace CircleCI.xcworkspace -scheme CircleCI
